# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set package registry
        run: echo @NAMESPACE:registry=https://npm.pkg.github.com >> .npmrc
      - run: npm i
      - run: npm run build
      - name: Remove src files
        run: rm -r -f src
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm i
      - run: npm run build
      - name: Remove src files
        run: rm -r -f src
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}
  
